version: "3.7"

services:
  db: 
    image: postgres:latest
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      POSTGRES_PASSWORD: ${password} 
      POSTGRES_USER: ${user}
      POSTGRES_DB: ${database}
    ports:
      - '${portDB}:${portDB}'
    expose:
      - "${portDB}"

  app:
    build: .
    command: npm start
    depends_on:
      - db
    ports:
      - "${portNode}:${portNode}"
    volumes:
      - .:/usr/app 


