version: "3.7"

services:
  db: 
    image: postgres:latest
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_USER: postgres
      POSTGRES_DB: simplecrud
    ports:
      - '5432:5432'
    expose:
      - "5432"

  app:
    build: .
    command: npm start
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app 


